INSERT INTO app_info (key , value ) VALUES ('logo' ,'logo.png ');
INSERT INTO app_info (key , value ) VALUES ('email' ,'store@gmail.com ');
INSERT INTO app_info (key , value ) VALUES ('phone' ,'9589559859 ');
INSERT INTO app_info (key , value ) VALUES ('address' ,'uabu dhabi united arab emarites');
INSERT INTO app_info (key , value ) VALUES ('app_store' ,'www.appstore.com ');
INSERT INTO app_info (key , value ) VALUES ('google_play' ,'www.googleplay.com');
INSERT INTO app_info (key , value ) VALUES ('facebook' ,'www.facebook.com');
INSERT INTO app_info (key , value ) VALUES ('twitter' ,'www.twitter.com');
INSERT INTO app_info (key , value ) VALUES ('snap' ,'www.snap.com');
INSERT INTO app_info (key , value ) VALUES ('instagram' ,'www.instagram.com');
INSERT INTO app_info (key , value ) VALUES ('About The App' ,'Our App is the best app for selling products online');